# SPDX-FileCopyrightText: 2024 Arm Limited and/or its affiliates <open-source-office@arm.com>
#
# SPDX-License-Identifier: Apache-2.0

image: registry.gitlab.arm.com/intrinsiccv/intrinsiccv:3

build:
  tags:
    - arm64
  script:
    - scripts/ci.sh
  artifacts:
    when: always
    expire_in: 1 day
    reports:
      junit: build/test-results/**/*.xml
      coverage_report:
        coverage_format: cobertura
        path: build/cobertura-coverage.xml
    paths:
      # GitLab Pages https://docs.gitlab.com/ee/user/project/pages/
      - public
