# SPDX-FileCopyrightText: 2024 Arm Limited and/or its affiliates <open-source-office@arm.com>
#
# SPDX-License-Identifier: Apache-2.0

image: registry.gitlab.arm.com/intrinsiccv/intrinsiccv:6

# Only run CI for main branch & merge requests
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

.common:
  tags:
    - arm64
  script:
    - scripts/ci.sh
  artifacts:
    when: always
    expire_in: 1 day
    reports:
      junit: build/test-results/**/*.xml
      coverage_report:
        coverage_format: cobertura
        path: build/cobertura-coverage.xml
    paths:
      - build/html
  coverage: /^line and branch coverage:\s+([\d\.]+\%)/

# On the main branch publish pages.
pages:
  extends: .common
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  publish: build/html

# On other branches don't publish pages.
test:
  extends: .common
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
